### ISSUE TITLE
Add new component to show latest balances 

### ISSUE THREAD

**Issue by ishaan-puniani** [ishaan-puniani/wallet-statistics#13]
Refer to the cards in http://localhost:6006/?path=/story/example-introduction--page
Show current balance of the partner in cards 

API:  /tenant/:tenantId/get-current-balances-for-transaction-types?filter[userId]=<partnerId>&filter[currency]=<INR/CCC/USD>

**Comment by Kushal0891** [comment]
@ishaan-puniani this done right ?

**Comment by ishaan-puniani** [comment]
Yes..
